# Generated by Django 4.0.3 on 2022-07-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='availibility',
        ),
    ]
